// Generated by gencpp from file polled_camera/GetPolledImage.msg
// DO NOT EDIT!


#ifndef POLLED_CAMERA_MESSAGE_GETPOLLEDIMAGE_H
#define POLLED_CAMERA_MESSAGE_GETPOLLEDIMAGE_H

#include <ros/service_traits.h>


#include <polled_camera/GetPolledImageRequest.h>
#include <polled_camera/GetPolledImageResponse.h>


namespace polled_camera
{

struct GetPolledImage
{

typedef GetPolledImageRequest Request;
typedef GetPolledImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPolledImage
} // namespace polled_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::polled_camera::GetPolledImage > {
  static const char* value()
  {
    return "1f3fb0d09d6e1c72d4a7eeb9822d9030";
  }

  static const char* value(const ::polled_camera::GetPolledImage&) { return value(); }
};

template<>
struct DataType< ::polled_camera::GetPolledImage > {
  static const char* value()
  {
    return "polled_camera/GetPolledImage";
  }

  static const char* value(const ::polled_camera::GetPolledImage&) { return value(); }
};


// service_traits::MD5Sum< ::polled_camera::GetPolledImageRequest> should match 
// service_traits::MD5Sum< ::polled_camera::GetPolledImage > 
template<>
struct MD5Sum< ::polled_camera::GetPolledImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::polled_camera::GetPolledImage >::value();
  }
  static const char* value(const ::polled_camera::GetPolledImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::polled_camera::GetPolledImageRequest> should match 
// service_traits::DataType< ::polled_camera::GetPolledImage > 
template<>
struct DataType< ::polled_camera::GetPolledImageRequest>
{
  static const char* value()
  {
    return DataType< ::polled_camera::GetPolledImage >::value();
  }
  static const char* value(const ::polled_camera::GetPolledImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::polled_camera::GetPolledImageResponse> should match 
// service_traits::MD5Sum< ::polled_camera::GetPolledImage > 
template<>
struct MD5Sum< ::polled_camera::GetPolledImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::polled_camera::GetPolledImage >::value();
  }
  static const char* value(const ::polled_camera::GetPolledImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::polled_camera::GetPolledImageResponse> should match 
// service_traits::DataType< ::polled_camera::GetPolledImage > 
template<>
struct DataType< ::polled_camera::GetPolledImageResponse>
{
  static const char* value()
  {
    return DataType< ::polled_camera::GetPolledImage >::value();
  }
  static const char* value(const ::polled_camera::GetPolledImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POLLED_CAMERA_MESSAGE_GETPOLLEDIMAGE_H
