; Auto-generated. Do not edit!


(cl:in-package kobuki_msgs-msg)


;//! \htmlinclude AutoDockingGoal.msg.html

(cl:defclass <AutoDockingGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass AutoDockingGoal (<AutoDockingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AutoDockingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AutoDockingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kobuki_msgs-msg:<AutoDockingGoal> is deprecated: use kobuki_msgs-msg:AutoDockingGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AutoDockingGoal>) ostream)
  "Serializes a message object of type '<AutoDockingGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AutoDockingGoal>) istream)
  "Deserializes a message object of type '<AutoDockingGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AutoDockingGoal>)))
  "Returns string type for a message object of type '<AutoDockingGoal>"
  "kobuki_msgs/AutoDockingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AutoDockingGoal)))
  "Returns string type for a message object of type 'AutoDockingGoal"
  "kobuki_msgs/AutoDockingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AutoDockingGoal>)))
  "Returns md5sum for a message object of type '<AutoDockingGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AutoDockingGoal)))
  "Returns md5sum for a message object of type 'AutoDockingGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AutoDockingGoal>)))
  "Returns full string definition for message of type '<AutoDockingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AutoDockingGoal)))
  "Returns full string definition for message of type 'AutoDockingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AutoDockingGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AutoDockingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AutoDockingGoal
))
