//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the baxter_interface package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __baxter_interface__POSITIONFFJOINTTRAJECTORYACTIONSERVERCONFIG_H__
#define __baxter_interface__POSITIONFFJOINTTRAJECTORYACTIONSERVERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace baxter_interface
{
  class PositionFFJointTrajectoryActionServerConfigStatics;

  class PositionFFJointTrajectoryActionServerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(PositionFFJointTrajectoryActionServerConfig &config, const PositionFFJointTrajectoryActionServerConfig &max, const PositionFFJointTrajectoryActionServerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PositionFFJointTrajectoryActionServerConfig &config1, const PositionFFJointTrajectoryActionServerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual void getValue(const PositionFFJointTrajectoryActionServerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PositionFFJointTrajectoryActionServerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (PositionFFJointTrajectoryActionServerConfig::* field);

      virtual void clamp(PositionFFJointTrajectoryActionServerConfig &config, const PositionFFJointTrajectoryActionServerConfig &max, const PositionFFJointTrajectoryActionServerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PositionFFJointTrajectoryActionServerConfig &config1, const PositionFFJointTrajectoryActionServerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PositionFFJointTrajectoryActionServerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PositionFFJointTrajectoryActionServerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PositionFFJointTrajectoryActionServerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PositionFFJointTrajectoryActionServerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PositionFFJointTrajectoryActionServerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PositionFFJointTrajectoryActionServerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PositionFFJointTrajectoryActionServerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PositionFFJointTrajectoryActionServerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("goal_time"==(*_i)->name){goal_time = boost::any_cast<double>(val);}
        if("stopped_velocity_tolerance"==(*_i)->name){stopped_velocity_tolerance = boost::any_cast<double>(val);}
        if("left_s0_goal"==(*_i)->name){left_s0_goal = boost::any_cast<double>(val);}
        if("left_s1_goal"==(*_i)->name){left_s1_goal = boost::any_cast<double>(val);}
        if("left_e0_goal"==(*_i)->name){left_e0_goal = boost::any_cast<double>(val);}
        if("left_e1_goal"==(*_i)->name){left_e1_goal = boost::any_cast<double>(val);}
        if("left_w0_goal"==(*_i)->name){left_w0_goal = boost::any_cast<double>(val);}
        if("left_w1_goal"==(*_i)->name){left_w1_goal = boost::any_cast<double>(val);}
        if("left_w2_goal"==(*_i)->name){left_w2_goal = boost::any_cast<double>(val);}
        if("right_s0_goal"==(*_i)->name){right_s0_goal = boost::any_cast<double>(val);}
        if("right_s1_goal"==(*_i)->name){right_s1_goal = boost::any_cast<double>(val);}
        if("right_e0_goal"==(*_i)->name){right_e0_goal = boost::any_cast<double>(val);}
        if("right_e1_goal"==(*_i)->name){right_e1_goal = boost::any_cast<double>(val);}
        if("right_w0_goal"==(*_i)->name){right_w0_goal = boost::any_cast<double>(val);}
        if("right_w1_goal"==(*_i)->name){right_w1_goal = boost::any_cast<double>(val);}
        if("right_w2_goal"==(*_i)->name){right_w2_goal = boost::any_cast<double>(val);}
        if("left_s0_trajectory"==(*_i)->name){left_s0_trajectory = boost::any_cast<double>(val);}
        if("left_s1_trajectory"==(*_i)->name){left_s1_trajectory = boost::any_cast<double>(val);}
        if("left_e0_trajectory"==(*_i)->name){left_e0_trajectory = boost::any_cast<double>(val);}
        if("left_e1_trajectory"==(*_i)->name){left_e1_trajectory = boost::any_cast<double>(val);}
        if("left_w0_trajectory"==(*_i)->name){left_w0_trajectory = boost::any_cast<double>(val);}
        if("left_w1_trajectory"==(*_i)->name){left_w1_trajectory = boost::any_cast<double>(val);}
        if("left_w2_trajectory"==(*_i)->name){left_w2_trajectory = boost::any_cast<double>(val);}
        if("right_s0_trajectory"==(*_i)->name){right_s0_trajectory = boost::any_cast<double>(val);}
        if("right_s1_trajectory"==(*_i)->name){right_s1_trajectory = boost::any_cast<double>(val);}
        if("right_e0_trajectory"==(*_i)->name){right_e0_trajectory = boost::any_cast<double>(val);}
        if("right_e1_trajectory"==(*_i)->name){right_e1_trajectory = boost::any_cast<double>(val);}
        if("right_w0_trajectory"==(*_i)->name){right_w0_trajectory = boost::any_cast<double>(val);}
        if("right_w1_trajectory"==(*_i)->name){right_w1_trajectory = boost::any_cast<double>(val);}
        if("right_w2_trajectory"==(*_i)->name){right_w2_trajectory = boost::any_cast<double>(val);}
      }
    }

    double goal_time;
double stopped_velocity_tolerance;
double left_s0_goal;
double left_s1_goal;
double left_e0_goal;
double left_e1_goal;
double left_w0_goal;
double left_w1_goal;
double left_w2_goal;
double right_s0_goal;
double right_s1_goal;
double right_e0_goal;
double right_e1_goal;
double right_w0_goal;
double right_w1_goal;
double right_w2_goal;
double left_s0_trajectory;
double left_s1_trajectory;
double left_e0_trajectory;
double left_e1_trajectory;
double left_w0_trajectory;
double left_w1_trajectory;
double left_w2_trajectory;
double right_s0_trajectory;
double right_s1_trajectory;
double right_e0_trajectory;
double right_e1_trajectory;
double right_w0_trajectory;
double right_w1_trajectory;
double right_w2_trajectory;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_time;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stopped_velocity_tolerance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s0_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s1_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e0_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e1_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w0_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w1_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w2_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s0_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s1_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e0_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e1_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w0_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w1_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w2_goal;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s0_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_s1_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e0_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_e1_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w0_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w1_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_w2_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s0_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_s1_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e0_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_e1_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w0_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w1_trajectory;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_w2_trajectory;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PositionFFJointTrajectoryActionServerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PositionFFJointTrajectoryActionServerConfig &__max__ = __getMax__();
      const PositionFFJointTrajectoryActionServerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PositionFFJointTrajectoryActionServerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PositionFFJointTrajectoryActionServerConfig &__getDefault__();
    static const PositionFFJointTrajectoryActionServerConfig &__getMax__();
    static const PositionFFJointTrajectoryActionServerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PositionFFJointTrajectoryActionServerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PositionFFJointTrajectoryActionServerConfig::ParamDescription<std::string>::clamp(PositionFFJointTrajectoryActionServerConfig &config, const PositionFFJointTrajectoryActionServerConfig &max, const PositionFFJointTrajectoryActionServerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PositionFFJointTrajectoryActionServerConfigStatics
  {
    friend class PositionFFJointTrajectoryActionServerConfig;

    PositionFFJointTrajectoryActionServerConfigStatics()
    {
PositionFFJointTrajectoryActionServerConfig::GroupDescription<PositionFFJointTrajectoryActionServerConfig::DEFAULT, PositionFFJointTrajectoryActionServerConfig> Default("Default", "", 0, 0, true, &PositionFFJointTrajectoryActionServerConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_time = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_time = 120.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_time = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("goal_time", "double", 0, "Amount of time (s) controller is permitted to be late achieving goal", "", &PositionFFJointTrajectoryActionServerConfig::goal_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("goal_time", "double", 0, "Amount of time (s) controller is permitted to be late achieving goal", "", &PositionFFJointTrajectoryActionServerConfig::goal_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stopped_velocity_tolerance = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stopped_velocity_tolerance = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stopped_velocity_tolerance = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("stopped_velocity_tolerance", "double", 0, "Maximum velocity (m/s) at end of trajectory to be considered stopped", "", &PositionFFJointTrajectoryActionServerConfig::stopped_velocity_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("stopped_velocity_tolerance", "double", 0, "Maximum velocity (m/s) at end of trajectory to be considered stopped", "", &PositionFFJointTrajectoryActionServerConfig::stopped_velocity_tolerance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s0_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s0_goal", "double", 0, "left_s0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_s0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s0_goal", "double", 0, "left_s0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_s0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s1_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s1_goal", "double", 0, "left_s1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_s1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s1_goal", "double", 0, "left_s1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_s1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e0_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e0_goal", "double", 0, "left_e0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_e0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e0_goal", "double", 0, "left_e0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_e0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e1_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e1_goal", "double", 0, "left_e1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_e1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e1_goal", "double", 0, "left_e1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_e1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w0_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w0_goal", "double", 0, "left_w0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_w0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w0_goal", "double", 0, "left_w0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_w0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w1_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w1_goal", "double", 0, "left_w1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_w1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w1_goal", "double", 0, "left_w1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_w1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w2_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w2_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w2_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w2_goal", "double", 0, "left_w2 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_w2_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w2_goal", "double", 0, "left_w2 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::left_w2_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s0_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s0_goal", "double", 0, "right_s0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_s0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s0_goal", "double", 0, "right_s0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_s0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s1_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s1_goal", "double", 0, "right_s1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_s1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s1_goal", "double", 0, "right_s1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_s1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e0_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e0_goal", "double", 0, "right_e0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_e0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e0_goal", "double", 0, "right_e0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_e0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e1_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e1_goal", "double", 0, "right_e1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_e1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e1_goal", "double", 0, "right_e1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_e1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w0_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w0_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w0_goal", "double", 0, "right_w0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_w0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w0_goal", "double", 0, "right_w0 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_w0_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w1_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w1_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w1_goal", "double", 0, "right_w1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_w1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w1_goal", "double", 0, "right_w1 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_w1_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w2_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w2_goal = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w2_goal = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w2_goal", "double", 0, "right_w2 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_w2_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w2_goal", "double", 0, "right_w2 - maximum final error", "", &PositionFFJointTrajectoryActionServerConfig::right_w2_goal)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s0_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s0_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s0_trajectory", "double", 0, "left_s0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_s0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s0_trajectory", "double", 0, "left_s0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_s0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_s1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_s1_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_s1_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s1_trajectory", "double", 0, "left_s1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_s1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_s1_trajectory", "double", 0, "left_s1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_s1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e0_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e0_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e0_trajectory", "double", 0, "left_e0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_e0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e0_trajectory", "double", 0, "left_e0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_e0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_e1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_e1_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_e1_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e1_trajectory", "double", 0, "left_e1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_e1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_e1_trajectory", "double", 0, "left_e1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_e1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w0_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w0_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w0_trajectory", "double", 0, "left_w0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_w0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w0_trajectory", "double", 0, "left_w0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_w0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w1_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w1_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w1_trajectory", "double", 0, "left_w1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_w1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w1_trajectory", "double", 0, "left_w1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_w1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_w2_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_w2_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_w2_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w2_trajectory", "double", 0, "left_w2 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_w2_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("left_w2_trajectory", "double", 0, "left_w2 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::left_w2_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s0_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s0_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s0_trajectory", "double", 0, "right_s0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_s0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s0_trajectory", "double", 0, "right_s0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_s0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_s1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_s1_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_s1_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s1_trajectory", "double", 0, "right_s1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_s1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_s1_trajectory", "double", 0, "right_s1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_s1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e0_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e0_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e0_trajectory", "double", 0, "right_e0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_e0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e0_trajectory", "double", 0, "right_e0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_e0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_e1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_e1_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_e1_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e1_trajectory", "double", 0, "right_e1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_e1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_e1_trajectory", "double", 0, "right_e1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_e1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w0_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w0_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w0_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w0_trajectory", "double", 0, "right_w0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_w0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w0_trajectory", "double", 0, "right_w0 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_w0_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w1_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w1_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w1_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w1_trajectory", "double", 0, "right_w1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_w1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w1_trajectory", "double", 0, "right_w1 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_w1_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_w2_trajectory = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_w2_trajectory = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_w2_trajectory = 0.35;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w2_trajectory", "double", 0, "right_w2 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_w2_trajectory)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("right_w2_trajectory", "double", 0, "right_w2 - maximum error during trajectory execution", "", &PositionFFJointTrajectoryActionServerConfig::right_w2_trajectory)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr(new PositionFFJointTrajectoryActionServerConfig::GroupDescription<PositionFFJointTrajectoryActionServerConfig::DEFAULT, PositionFFJointTrajectoryActionServerConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PositionFFJointTrajectoryActionServerConfig __max__;
    PositionFFJointTrajectoryActionServerConfig __min__;
    PositionFFJointTrajectoryActionServerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PositionFFJointTrajectoryActionServerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PositionFFJointTrajectoryActionServerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PositionFFJointTrajectoryActionServerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PositionFFJointTrajectoryActionServerConfig &PositionFFJointTrajectoryActionServerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PositionFFJointTrajectoryActionServerConfig &PositionFFJointTrajectoryActionServerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PositionFFJointTrajectoryActionServerConfig &PositionFFJointTrajectoryActionServerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr> &PositionFFJointTrajectoryActionServerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> &PositionFFJointTrajectoryActionServerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PositionFFJointTrajectoryActionServerConfigStatics *PositionFFJointTrajectoryActionServerConfig::__get_statics__()
  {
    const static PositionFFJointTrajectoryActionServerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PositionFFJointTrajectoryActionServerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __POSITIONFFJOINTTRAJECTORYACTIONSERVERRECONFIGURATOR_H__
