// Generated by gencpp from file controller_manager_msgs/LoadController.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MANAGER_MSGS_MESSAGE_LOADCONTROLLER_H
#define CONTROLLER_MANAGER_MSGS_MESSAGE_LOADCONTROLLER_H

#include <ros/service_traits.h>


#include <controller_manager_msgs/LoadControllerRequest.h>
#include <controller_manager_msgs/LoadControllerResponse.h>


namespace controller_manager_msgs
{

struct LoadController
{

typedef LoadControllerRequest Request;
typedef LoadControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadController
} // namespace controller_manager_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller_manager_msgs::LoadController > {
  static const char* value()
  {
    return "647e5c54b8d6468952d8d31f1efe96c0";
  }

  static const char* value(const ::controller_manager_msgs::LoadController&) { return value(); }
};

template<>
struct DataType< ::controller_manager_msgs::LoadController > {
  static const char* value()
  {
    return "controller_manager_msgs/LoadController";
  }

  static const char* value(const ::controller_manager_msgs::LoadController&) { return value(); }
};


// service_traits::MD5Sum< ::controller_manager_msgs::LoadControllerRequest> should match 
// service_traits::MD5Sum< ::controller_manager_msgs::LoadController > 
template<>
struct MD5Sum< ::controller_manager_msgs::LoadControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller_manager_msgs::LoadController >::value();
  }
  static const char* value(const ::controller_manager_msgs::LoadControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_manager_msgs::LoadControllerRequest> should match 
// service_traits::DataType< ::controller_manager_msgs::LoadController > 
template<>
struct DataType< ::controller_manager_msgs::LoadControllerRequest>
{
  static const char* value()
  {
    return DataType< ::controller_manager_msgs::LoadController >::value();
  }
  static const char* value(const ::controller_manager_msgs::LoadControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller_manager_msgs::LoadControllerResponse> should match 
// service_traits::MD5Sum< ::controller_manager_msgs::LoadController > 
template<>
struct MD5Sum< ::controller_manager_msgs::LoadControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller_manager_msgs::LoadController >::value();
  }
  static const char* value(const ::controller_manager_msgs::LoadControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_manager_msgs::LoadControllerResponse> should match 
// service_traits::DataType< ::controller_manager_msgs::LoadController > 
template<>
struct DataType< ::controller_manager_msgs::LoadControllerResponse>
{
  static const char* value()
  {
    return DataType< ::controller_manager_msgs::LoadController >::value();
  }
  static const char* value(const ::controller_manager_msgs::LoadControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MANAGER_MSGS_MESSAGE_LOADCONTROLLER_H
