(cl:in-package create_node-msg)
(cl:export '(HEADER-VAL
          HEADER
          BUMPS_WHEELDROPS-VAL
          BUMPS_WHEELDROPS
          WALL-VAL
          WALL
          CLIFF_LEFT-VAL
          CLIFF_LEFT
          CLIFF_FRONT_LEFT-VAL
          CLIFF_FRONT_LEFT
          CLIFF_FRONT_RIGHT-VAL
          CLIFF_FRONT_RIGHT
          CLIFF_RIGHT-VAL
          CLIFF_RIGHT
          VIRTUAL_WALL-VAL
          VIRTUAL_WALL
          MOTOR_OVERCURRENTS-VAL
          MOTOR_OVERCURRENTS
          DIRT_DETECTOR_LEFT-VAL
          DIRT_DETECTOR_LEFT
          DIRT_DETECTOR_RIGHT-VAL
          DIRT_DETECTOR_RIGHT
          REMOTE_OPCODE-VAL
          REMOTE_OPCODE
          BUTTONS-VAL
          BUTTONS
          DISTANCE-VAL
          DISTANCE
          ANGLE-VAL
          ANGLE
          CHARGING_STATE-VAL
          CHARGING_STATE
          VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          TEMPERATURE-VAL
          TEMPERATURE
          CHARGE-VAL
          CHARGE
          CAPACITY-VAL
          CAPACITY
))