# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yocs_msgs/NavigateToGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NavigateToGoal(genpy.Message):
  _md5sum = "1549bb00469af4886dd492a95637d796"
  _type = "yocs_msgs/NavigateToGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Goal
string location
int8   approach_type
int8   num_retry
float32 timeout

# This variable used when approach near is requested
float32 distance

int8 APPROACH_NEAR = 11
int8 APPROACH_ON   = 12
"""
  # Pseudo-constants
  APPROACH_NEAR = 11
  APPROACH_ON = 12

  __slots__ = ['location','approach_type','num_retry','timeout','distance']
  _slot_types = ['string','int8','int8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       location,approach_type,num_retry,timeout,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NavigateToGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.location is None:
        self.location = ''
      if self.approach_type is None:
        self.approach_type = 0
      if self.num_retry is None:
        self.num_retry = 0
      if self.timeout is None:
        self.timeout = 0.
      if self.distance is None:
        self.distance = 0.
    else:
      self.location = ''
      self.approach_type = 0
      self.num_retry = 0
      self.timeout = 0.
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.location
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2b2f().pack(_x.approach_type, _x.num_retry, _x.timeout, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location = str[start:end].decode('utf-8')
      else:
        self.location = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.approach_type, _x.num_retry, _x.timeout, _x.distance,) = _get_struct_2b2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.location
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2b2f().pack(_x.approach_type, _x.num_retry, _x.timeout, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location = str[start:end].decode('utf-8')
      else:
        self.location = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.approach_type, _x.num_retry, _x.timeout, _x.distance,) = _get_struct_2b2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b2f = None
def _get_struct_2b2f():
    global _struct_2b2f
    if _struct_2b2f is None:
        _struct_2b2f = struct.Struct("<2b2f")
    return _struct_2b2f
