(cl:in-package baxter_core_msgs-msg)
(cl:export '(ID-VAL
          ID
          UI_TYPE-VAL
          UI_TYPE
          MANUFACTURER-VAL
          MANUFACTURER
          PRODUCT-VAL
          PRODUCT
          SERIAL_NUMBER-VAL
          SERIAL_NUMBER
          HARDWARE_REV-VAL
          HARDWARE_REV
          FIRMWARE_REV-VAL
          FIRMWARE_REV
          FIRMWARE_DATE-VAL
          FIRMWARE_DATE
          HAS_CALIBRATION-VAL
          HAS_CALIBRATION
          CONTROLS_GRIP-VAL
          CONTROLS_GRIP
          SENSES_GRIP-VAL
          SENSES_GRIP
          REVERSES_GRIP-VAL
          REVERSES_GRIP
          CONTROLS_FORCE-VAL
          CONTROLS_FORCE
          SENSES_FORCE-VAL
          SENSES_FORCE
          CONTROLS_POSITION-VAL
          CONTROLS_POSITION
          SENSES_POSITION-VAL
          SENSES_POSITION
          PROPERTIES-VAL
          PROPERTIES
))