(cl:defpackage yocs_msgs-srv
  (:use )
  (:export
   "WAYPOINTLISTSERVICE"
   "<WAYPOINTLISTSERVICE-REQUEST>"
   "WAYPOINTLISTSERVICE-REQUEST"
   "<WAYPOINTLISTSERVICE-RESPONSE>"
   "WAYPOINTLISTSERVICE-RESPONSE"
  ))

